added contents to lov.ttl
nl-digigo/nen2660 pull request #7
Opened 2022-07-06 13:15 UTC by RiX012

2022-07-06 13:15 UTC, RiX012 reviewed
@redmer. Check vooral ook even of ik de juiste namespaces en URI's gebruikt hebt.

2022-07-06 15:05 UTC, redmer requested changes
Ziet er goed uit, een paar kleine aanpassingen zijn nog nodig.

2022-07-06 15:05 UTC, redmer commented on data/metadata/lov.ttl
> +                rdfs:label "Stichting CROW"@nl .
`<http://www.nen.nl>` en <`http://www.crow.nl>` i.p.v. `<www....>`

2022-07-06 15:05 UTC, redmer commented on data/metadata/lov.ttl
> +nen2660:AbstractConcept vs:term_status "stable"@en;
NEN 2660-2 gebruikt en schrijft voor `skos:prefLabel` voor de labels van de onderdelen. In https://lov.linkeddata.es/Recommendations_Vocabulary_Design.pdf staat dat `rdfs:label` gebruikt moet worden daarvoor. Nu als we SKOS importeren, dan is er een triple `skos:prefLabel rdfs:subPropertyOf rdfs:label`, waardoor het wellicht door de inferecing geregeld kan zijn.

2022-07-06 15:05 UTC, redmer commented on data/metadata/lov.ttl
> +nen2660-term:AbstractConcept vs:term_status "stable"@en;
```xml
<rdf:Property rdf:about="#term_status">
  <rdfs:label>term status</rdfs:label>
  <rdfs:comment>the status of a vocabulary term, expressed as a short symbolic string; known values include 'unstable','testing', 'stable' and 'archaic'</rdfs:comment>
  <vs:term_status>unstable</vs:term_status>
  <rdfs:isDefinedBy rdf:resource="http://www.w3.org/2003/06/sw-vocab-status/ns#"/>	
</rdf:Property>
```

Ik denk dat de waarde dan `"stable"` moet zijn, niet een `rdf:langString` .

2022-07-06 15:05 UTC, redmer commented on data/metadata/lov.ttl
> +                rdfs:label "Stichting CROW"@nl .
Voorts prima manier imho om naar beide organisaties te verwijzen.

2022-07-07 07:48 UTC, RiX012 commented on data/metadata/lov.ttl
> +                rdfs:label "Stichting CROW"@nl .
Goed punt

2022-07-07 07:50 UTC, RiX012 commented on data/metadata/lov.ttl
> +nen2660:AbstractConcept vs:term_status "stable"@en;
Ja dat klopt. Ik denk dus inderdaad dat we het op voc niveau rdfs:label mogen houden (daar zegt NEN2660 toch niet over). En binnen de ontology skos:prefLabel

2022-07-07 07:51 UTC, RiX012 commented on data/metadata/lov.ttl
> +nen2660-term:AbstractConcept vs:term_status "stable"@en;
OK, dus zonder @en bedoel je he. Prima

2022-07-07 07:52 UTC, RiX012 commented
OK, aanpassing gedaan!

2022-07-08 10:12 UTC, redmer approved these changes

2022-07-08 10:13 UTC, merged